Repository KhronosGroup/Vulkan-Docs, pull requests merged in 2021-06, with the labels that each got.

#1535 Add another missing optional
  xml/vk.xml
Labels: Video

#1356 Add specification for VK_EXT_physical_device_drm
  appendices/VK_EXT_physical_device_drm.txt
  chapters/devsandqueues.txt
  xml/vk.xml
Labels: Extension, System Integration

#1538 vk.xml: Include `vk_platform` type-header from `vulkan/vk_platform.h`
  xml/vk.xml
Labels: Header, Resolving Inside Khronos, Video
